# This workflow run security tests and send message for orgs into chat
# -679349277
name: Check it!

on:

  pull_request:
    branches:
      - checked
    types: [opened, reopened]

jobs:
  security-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: Andrianov-Artemii/ppt-solutions-2022/.github/actions/checkit.yml@master
