# This workflow run security tests and send message for orgs into chat
# -679349277
name: Check it!

on:
  issue_comment:
    types:
      - created

jobs:
  security-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v2
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Send hello
    - name: Send request
      if: ${{ contains(github.event.comment.body, '/checkit') && github.base_ref == 'checked' }}
      uses: appleboy/telegram-action@master
      with:
        to: "-679349277"
        token: "5292735252:AAHbDsG2pWZlYYTlUVOdwE4scVs7c62lz7U"
        message: |
            ❇️ ${{ github.actor }} подал новую заявку на проверку! ❇️            
            Ссылка на pull: https://github.com/${{ github.repository }}/commit/${{github.sha}}
    