# This workflow run security tests and send message for orgs into chat
# -679349277
name: Check it!

on:
  issue_comment:
    types:
      - created

jobs:
  security-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v2
    - name: Send hello
      run: echo ${{ github.event.comment.body }}
    - name: Send request
      if: contains(github.event.comment.body, '/checkit') && branch == 'checked'
      uses: appleboy/telegram-action@master
      with:
        to: "-679349277"
        token: "5292735252:AAHbDsG2pWZlYYTlUVOdwE4scVs7c62lz7U"
        message: |
            ❇️ ${{ github.actor }} подал новую заявку на проверку! ❇️            
            Ссылка на pull: https://github.com/${{ github.repository }}/commit/${{github.sha}}
    