# This workflow run security tests and send message for orgs into chat
# -679349277
name: Check it!

on:

  pull_request:
    branches:
      - checked
    types: [opened, reopened]

jobs:
  security-tests:
    runs-on: ubuntu-latest
    steps:
    - name: github dump
      env:
        dump: ${{ toJson(github)}}
      run: echo "$dump"
    - name: Send request
      uses: appleboy/telegram-action@master
      with:
        to: "-679349277"
        token: "5292735252:AAHbDsG2pWZlYYTlUVOdwE4scVs7c62lz7U"
        message: |
            ${{ github.actor }} переоткрыл заявку на проверку, надо поглазеть👀!         
            Ссылка на PR: ${{github.pull_request._links.html.href}}
    