# This workflow run security tests and send message for orgs into chat
# -679349277
name: Check it!

on:
  pull_request:
    branches:
      - checked
    types: [opened, reopened]

jobs:
  print-test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo 'test'
  security-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        uses: Andrianov-Artemii/ppt-solutions-2022/actions/ppt-alert-bot@master
        with:
          input-keys: checkit ${{ github.repository }} ${{github.event.pull_request._links.html.href}}
  send_instructions:
    needs: [ security-tests ]
    runs-on: ubuntu-latest
    name: Send instructions for parts
    if: ${{ github.event.action == 'reopened' }}
    steps:
      - name: Send instructions
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: '❇️Вы открыли PR на проверку решения❇️
          Я уже сообщил организаторам, что вы готовы к проверке, они скоро придут и посмотрят ваше решение
          ❗️Не делайте merge пул реквеста сами, иначе оно не будет проверено❗️'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}