# This workflow run security tests and send message for orgs into chat
# -679349277
name: Check it!

on:
  pull_request:
    branches:
      - checked
    types: [opened, reopened]

jobs:
  print-test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo 'test'
  security-tests:
    runs-on: ubuntu-latest
    container:
      image: docker pull andrianovartemii/checkit
      env: 
        params: ban Andrianov-Artemii https://github.com/
    steps:
      - name: wait resp
        run: echo 'resp'
