# This workflow run security tests and send message for orgs into chat
# -679349277
name: Check it!

on:
  pull_request:
    branches:
      - checked
    types: [opened, reopened]

jobs:
  print-test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo 'test'
  security-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        uses: Andrianov-Artemii/ppt-solutions-2022/actions/ppt-alert-bot@master
        with:
          input-keys: checkit ${{ github.actor }} ${{github.event.pull_request._links.html.href}}