# This workflow run security tests and send message for orgs into chat

name: Check it!

on:
  pull_request:
    branches: [ checked ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: 3.10

    steps:
    - uses: actions/checkout@v2
    - name: Send hello
      run: echo "Hello"
