#Start when checked pull request was close 
name: onclose

on:
  pull_request:
    branches: [checked]
    types: [ closed]
  
jobs:
  send-instructions:
    runs-on: ubuntu-latest
    steps:
      - name: Send instructions 
        uses: thollander/actions-comment-pull-request@v1
        
        with:
          message: '${{ github.actor }} закрыл ваше решение, переоткройте его, когда будете готовы к повторный проверке!'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}