name: Push tests

on: [ push, workflow_call ]

jobs:   

  check_commit:
    runs-on: ubuntu-latest
    name: Check commit
    steps: 
      - uses: actions/checkout@v2
      - name: Checking for the existence of tasks-dir
        run: |
          (test ! -d ${ GITHUB_WORKSPACE }/ppt-task1-younger-brother) && exit 1 
          (test ! -d ${ GITHUB_WORKSPACE }/ppt-task2-older-brother) && exit 1
          (test ! -d ${ GITHUB_WORKSPACE }/ppt-task3-supreme-commander) && exit 1 


  check_push_context:
    runs-on: ubuntu-latest
    name: Checking push conditions
    if: ${{ github.event_name != 'workflow_call' && false }}
    steps:
      - name: Check publication time
        id: cond-checks
        uses: Andrianov-Artemii/ppt-solutions-2022/actions/ppt-alert-bot@master
        with:
          input-keys: push ${{ github.repository }} ${{github.event.commits[0].url}}

  build:
    runs-on: ubuntu-latest
    #needs: [check_push_context]
    name: Build your solutions
    steps:
      - uses: actions/checkout@v2
      - name: Docker compose containers
        working-directory: .
        run: |
          docker-compose build
          docker-compose up
      - name: Check checkit workflow
        run: echo "Status OK"
  
