name: Push tests

on: [ push, workflow_call ]

jobs:   

  compare_files:
    name: compare
    runs-on: ubuntu-latest
    steps:
      - run: |
          # if cmp -s "./github/workflow" "Andrianov-Artemii/ppt-check-ex./github/workflow"  then
              printf 'status ok!'
          else
              printf 'status 500!'
          fi
        
  check_push_context:
    name: Check push conditions and run tests
    uses: Andrianov-Artemii/ppt-solutions-2022/.github/workflows/onpush-in-repo.yml@master