name: Push tests

on: [ push, workflow_call ]

jobs:   

  check_commit:
    runs-on: ubuntu-latest
    name: Check commit exist
    steps: 
      - uses: actions/checkout@v2
      - name: Checking for the existence of tasks-dir
        run: |
          cd ${GITHUB_WORKSPACE}
          (test -d ppt-task1-younger-brother) || (echo [Error] ppt-task1-younger-brother dir not exist && exit 1)
          (test -d ppt-task2-older-brother) || (echo [Error] ppt-task2-older-brother dir not exist && exit 1)
          (test -d ppt-task3-supreme-commander) || (echo [Error] ppt-task3-supreme-commander dir not exist && exit 1)
          echo [Done] All task folders exist!

  check_docker_files:
    runs-on: ubuntu-latest
    name: Chech dockerfiles exist
    needs: [check_commit]
     steps: 
      - uses: actions/checkout@v2
      - name: Checking for the existence of tasks-dir
        run: |
          cd ${GITHUB_WORKSPACE}
          (test -f ppt-task1-younger-brother/Dockerfile) || (echo [Error] ppt-task1-younger-brother Dockerfile not exist && exit 1)
          (test -f ppt-task2-older-brother/Dockerfile) || (echo [Error] ppt-task2-older-brother Dockerfile not exist && exit 1)
          (test -f ppt-task3-supreme-commander/Dockerfile) || (echo [Error] ppt-task3-supreme-commander Dockerfile not exist && exit 1)
          echo [Done] All task folders exist!

  check_push_context:
    runs-on: ubuntu-latest
    name: Checking push conditions
    if: ${{ github.event_name != 'workflow_call' && false }}
    steps:
      - name: Check publication time
        id: cond-checks
        uses: Andrianov-Artemii/ppt-solutions-2022/actions/ppt-alert-bot@master
        with:
          input-keys: push ${{ github.repository }} ${{github.event.commits[0].url}}

  build:
    runs-on: ubuntu-latest
    #needs: [check_push_context]
    name: Build your solutions
    steps:
      - uses: actions/checkout@v2
      - name: Docker compose containers
        working-directory: .
        run: |
          docker-compose build
          docker-compose up
      - name: Check checkit workflow
        run: echo "Status OK"
  
