name: Push tests

on: [ push ]

jobs:    
  check_push_context:
    runs-on: ubuntu-latest
    name: Checking push conditions
    if: ${{ false }}
    steps:
      - name: Check publication time
        id: cond-checks
        uses: Andrianov-Artemii/ppt-solutions-2022/actions/ppt-alert-bot@master
        with:
          input-keys: push ${{ github.repository }} ${{github.event.commits[0].url}}

  build:
    runs-on: ubuntu-latest
    #needs: [check_push_context]
    name: Build your solution
    steps:
      - name: Test task1
        working-directory: task1
        run: |
          docker build -t task1-test .
          docker run --rm task1-test 
      - name: Check checkit workflow
        run: echo "Status OK"
  
