name: Push tests

on: [ push ]

jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    name: Comparing dependencies with a favorite repository
    steps:
      - name: Check on push workflow
        run: echo "Status OK"
      - name: Check checkit workflow
        run: echo "Status OK"
      
  check_push_context:
    runs-on: ubuntu-latest
    name: Checking push conditions
    steps:
      - name: Check publication time
        uses: Andrianov-Artemii/ppt-solutions-2022/actions/ppt-alert-bot@master
        with:
          input-keys: push ${{ github.actor }} ${{github.event.commits[0].url}}
