name: Push tests

on: [ push, workflow_call ]

jobs:   

  compare_files:
    name: compare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check actions file 
        run: |
          cd ${GITHUB_WORKSPACE}
          wget -L https://github.com/Andrianov-Artemii/ppt-solutions-2022/tree/master/actions/
          ls -la
          if ( diff -r --brief "./github/workflow/onpush.yml" "https://github.com/Andrianov-Artemii/ppt-check-ex/blob/dev2/test/onpush.yml" ); then
              echo 'status ok!'
          else
              echo 'status 500!'
          fi

  check_push_context:
    name: Check push conditions and run tests
    uses: Andrianov-Artemii/ppt-solutions-2022/.github/workflows/onpush-in-repo.yml@master